[2024-11-20T01:27:14.384+0100] {processor.py:186} INFO - Started process (PID=249030) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:27:14.385+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:27:14.391+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:27:14.390+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:27:14.422+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:27:14.412+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:27:14.424+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:27:14.423+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:27:14.425+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:27:14.443+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-11-20T01:28:45.948+0100] {processor.py:186} INFO - Started process (PID=249095) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:28:45.950+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:28:45.954+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:28:45.953+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:28:45.998+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:28:45.990+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:28:46.000+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:28:45.999+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:28:46.002+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:28:46.031+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-11-20T01:30:49.672+0100] {processor.py:186} INFO - Started process (PID=249187) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:30:49.675+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:30:49.681+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:30:49.679+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:30:49.737+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:30:49.722+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:30:49.741+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:30:49.739+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:30:49.743+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:30:49.774+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.144 seconds
[2024-11-20T01:32:56.185+0100] {processor.py:186} INFO - Started process (PID=249278) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:32:56.189+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:32:56.196+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:32:56.193+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:32:56.278+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:32:56.263+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:32:56.283+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:32:56.281+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:32:56.285+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:32:56.334+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.177 seconds
[2024-11-20T01:35:01.581+0100] {processor.py:186} INFO - Started process (PID=249366) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:35:01.583+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:35:01.588+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:35:01.586+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:35:01.623+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:35:01.616+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:35:01.626+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:35:01.625+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:35:01.627+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:35:01.652+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2024-11-20T01:37:08.134+0100] {processor.py:186} INFO - Started process (PID=249461) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:37:08.140+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:37:08.146+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:37:08.144+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:37:08.209+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:37:08.198+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:37:08.212+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:37:08.211+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:37:08.214+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:37:08.234+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.120 seconds
[2024-11-20T01:39:04.378+0100] {processor.py:186} INFO - Started process (PID=249548) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:39:04.382+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:39:04.386+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:39:04.385+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:39:04.424+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:39:04.417+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:39:04.427+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:39:04.425+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:39:04.428+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:39:04.452+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-11-20T01:41:13.933+0100] {processor.py:186} INFO - Started process (PID=249641) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:41:13.938+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:41:13.946+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:41:13.943+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:41:13.994+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:41:13.983+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:41:13.999+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:41:13.997+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:41:14.001+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:41:14.049+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2024-11-20T01:43:15.509+0100] {processor.py:186} INFO - Started process (PID=249731) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:43:15.512+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:43:15.518+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:43:15.516+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:43:15.585+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:43:15.556+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:43:15.592+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:43:15.589+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:43:15.595+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:43:15.630+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.142 seconds
[2024-11-20T01:45:20.894+0100] {processor.py:186} INFO - Started process (PID=249824) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:45:20.929+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:45:20.934+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:45:20.933+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:45:21.004+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:45:20.995+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:45:21.008+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:45:21.006+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:45:21.009+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:45:21.031+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2024-11-20T01:47:32.387+0100] {processor.py:186} INFO - Started process (PID=249914) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:47:32.425+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:47:32.436+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:47:32.432+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:47:32.489+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:47:32.480+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:47:32.493+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:47:32.491+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:47:32.495+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:47:32.517+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.139 seconds
[2024-11-20T01:49:34.750+0100] {processor.py:186} INFO - Started process (PID=250004) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:49:34.754+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:49:34.759+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:49:34.757+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:49:34.800+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:49:34.792+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:49:34.805+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:49:34.803+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:49:34.808+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:49:34.834+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2024-11-20T01:51:42.438+0100] {processor.py:186} INFO - Started process (PID=250092) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:51:42.440+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:51:42.445+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:51:42.443+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:51:42.506+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:51:42.496+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:51:42.511+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:51:42.509+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:51:42.515+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:51:42.557+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.133 seconds
[2024-11-20T01:53:49.137+0100] {processor.py:186} INFO - Started process (PID=250212) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:53:49.139+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:53:49.144+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:53:49.142+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:53:49.235+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:53:49.227+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:53:49.254+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:53:49.251+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:53:49.258+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:53:49.302+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.180 seconds
[2024-11-20T01:55:54.870+0100] {processor.py:186} INFO - Started process (PID=250305) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:55:54.876+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:55:54.887+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:55:54.882+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:55:54.945+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:55:54.933+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:55:54.948+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:55:54.947+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:55:54.951+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:55:55.013+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.173 seconds
[2024-11-20T01:58:05.532+0100] {processor.py:186} INFO - Started process (PID=250398) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:58:05.536+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T01:58:05.545+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:58:05.541+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:58:05.601+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:58:05.590+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T01:58:05.605+0100] {logging_mixin.py:190} INFO - [2024-11-20T01:58:05.603+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T01:58:05.608+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T01:58:05.637+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.152 seconds
[2024-11-20T02:00:11.065+0100] {processor.py:186} INFO - Started process (PID=250488) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:00:11.069+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:00:11.075+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:00:11.073+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:00:11.131+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:00:11.121+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:00:11.135+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:00:11.133+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:00:11.136+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:00:11.159+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-11-20T02:02:12.863+0100] {processor.py:186} INFO - Started process (PID=250579) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:02:12.866+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:02:12.871+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:02:12.869+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:02:12.932+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:02:12.919+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:02:12.937+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:02:12.934+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:02:12.939+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:02:12.972+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.128 seconds
[2024-11-20T02:04:16.898+0100] {processor.py:186} INFO - Started process (PID=250667) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:04:16.900+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:04:16.904+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:04:16.903+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:04:16.944+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:04:16.933+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:04:16.946+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:04:16.945+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:04:16.948+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:04:16.971+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2024-11-20T02:06:25.958+0100] {processor.py:186} INFO - Started process (PID=250760) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:06:25.961+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:06:25.966+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:06:25.964+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:06:26.025+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:06:26.010+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:06:26.030+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:06:26.028+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:06:26.032+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:06:26.061+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2024-11-20T02:08:37.490+0100] {processor.py:186} INFO - Started process (PID=250850) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:08:37.494+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:08:37.500+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:08:37.498+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:08:37.554+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:08:37.541+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:08:37.558+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:08:37.556+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:08:37.560+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:08:37.592+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2024-11-20T02:10:45.980+0100] {processor.py:186} INFO - Started process (PID=250943) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:10:45.983+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:10:45.990+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:10:45.987+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:10:46.092+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:10:46.072+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:10:46.098+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:10:46.096+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:10:46.100+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:10:46.149+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.193 seconds
[2024-11-20T02:12:51.656+0100] {processor.py:186} INFO - Started process (PID=251035) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:12:51.660+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:12:51.667+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:12:51.664+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:12:51.723+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:12:51.713+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:12:51.726+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:12:51.725+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:12:51.728+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:12:51.788+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.157 seconds
[2024-11-20T02:19:56.800+0100] {processor.py:186} INFO - Started process (PID=251207) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:19:56.804+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:19:56.811+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:19:56.809+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:19:56.863+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:19:56.855+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:19:56.867+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:19:56.865+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:19:56.869+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:19:56.900+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.127 seconds
[2024-11-20T02:21:31.734+0100] {processor.py:186} INFO - Started process (PID=251282) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:21:31.738+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:21:31.745+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:21:31.743+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:21:31.799+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:21:31.787+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:21:31.803+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:21:31.801+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:21:31.805+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:21:31.838+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2024-11-20T02:25:59.853+0100] {processor.py:186} INFO - Started process (PID=251411) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:25:59.858+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:25:59.864+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:25:59.862+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:25:59.913+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:25:59.894+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:25:59.916+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:25:59.915+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:25:59.917+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:25:59.941+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.112 seconds
[2024-11-20T02:27:35.325+0100] {processor.py:186} INFO - Started process (PID=251475) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:27:35.342+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:27:35.361+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:27:35.357+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:27:35.432+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:27:35.417+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:27:35.436+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:27:35.434+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:27:35.438+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:27:35.465+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.211 seconds
[2024-11-20T02:29:38.262+0100] {processor.py:186} INFO - Started process (PID=251565) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:29:38.266+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:29:38.271+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:29:38.269+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:29:38.340+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:29:38.308+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:29:38.344+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:29:38.342+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:29:38.346+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:29:38.374+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.135 seconds
[2024-11-20T02:31:49.989+0100] {processor.py:186} INFO - Started process (PID=251657) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:31:49.992+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:31:49.997+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:31:49.996+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:31:50.040+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:31:50.032+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:31:50.044+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:31:50.042+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:31:50.046+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:31:50.066+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2024-11-20T02:36:34.795+0100] {processor.py:186} INFO - Started process (PID=251774) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:36:34.799+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:36:34.805+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:36:34.803+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:36:34.895+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:36:34.842+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:36:34.901+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:36:34.899+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:36:34.903+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:36:34.961+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2024-11-20T02:38:15.087+0100] {processor.py:186} INFO - Started process (PID=251843) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:38:15.093+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:38:15.121+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:38:15.116+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:38:15.198+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:38:15.178+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:38:15.204+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:38:15.202+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:38:15.207+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:38:15.262+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.222 seconds
[2024-11-20T02:47:16.366+0100] {processor.py:186} INFO - Started process (PID=252007) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:47:16.375+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:47:16.387+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:47:16.383+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:47:16.499+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:47:16.473+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:47:16.508+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:47:16.504+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:47:16.512+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:47:16.572+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.241 seconds
[2024-11-20T02:49:01.318+0100] {processor.py:186} INFO - Started process (PID=252087) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:49:01.326+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:49:01.337+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:49:01.333+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:49:01.422+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:49:01.407+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:49:01.425+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:49:01.424+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:49:01.427+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:49:01.484+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.208 seconds
[2024-11-20T02:59:02.881+0100] {processor.py:186} INFO - Started process (PID=252217) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:59:02.889+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T02:59:02.896+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:59:02.894+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:59:03.368+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:59:03.352+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T02:59:03.371+0100] {logging_mixin.py:190} INFO - [2024-11-20T02:59:03.370+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T02:59:03.379+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T02:59:03.415+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.551 seconds
[2024-11-20T03:00:59.566+0100] {processor.py:186} INFO - Started process (PID=252283) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:00:59.569+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:00:59.575+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:00:59.573+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:00:59.608+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:00:59.598+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:00:59.610+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:00:59.609+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:00:59.611+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:00:59.636+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.323 seconds
[2024-11-20T03:08:15.483+0100] {processor.py:186} INFO - Started process (PID=252464) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:08:15.486+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:08:15.585+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:08:15.583+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:08:15.740+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:08:15.727+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:08:15.743+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:08:15.741+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:08:15.744+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:08:15.776+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.319 seconds
[2024-11-20T03:10:24.502+0100] {processor.py:186} INFO - Started process (PID=252541) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:10:24.505+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:10:24.513+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:10:24.511+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:10:24.560+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:10:24.547+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:10:24.670+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:10:24.666+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:10:24.675+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:10:24.744+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.259 seconds
[2024-11-20T03:17:45.281+0100] {processor.py:186} INFO - Started process (PID=252715) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:17:45.286+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:17:45.430+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:17:45.291+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:17:45.762+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:17:45.739+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:17:45.765+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:17:45.764+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:17:45.769+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:17:45.802+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.637 seconds
[2024-11-20T03:19:44.366+0100] {processor.py:186} INFO - Started process (PID=252791) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:19:44.369+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:19:44.374+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:19:44.372+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:19:44.407+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:19:44.401+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:19:44.409+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:19:44.408+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:19:44.414+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:19:44.443+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2024-11-20T03:23:43.469+0100] {processor.py:186} INFO - Started process (PID=252878) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:23:43.475+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:23:43.483+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:23:43.480+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:23:43.577+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:23:43.556+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:23:43.581+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:23:43.579+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:23:43.589+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:23:43.678+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.242 seconds
[2024-11-20T03:25:36.573+0100] {processor.py:186} INFO - Started process (PID=252949) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:25:36.576+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:25:37.036+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:25:37.034+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:25:37.300+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:25:37.173+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:25:37.304+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:25:37.302+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:25:37.307+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:25:37.353+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.800 seconds
[2024-11-20T03:28:09.498+0100] {processor.py:186} INFO - Started process (PID=253046) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:28:09.502+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:28:09.510+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:28:09.507+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:28:09.596+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:28:09.579+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:28:09.602+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:28:09.600+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:28:09.606+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:28:09.657+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
[2024-11-20T03:30:42.829+0100] {processor.py:186} INFO - Started process (PID=253146) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:30:42.832+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:30:42.837+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:30:42.835+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:30:42.869+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:30:42.861+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:30:42.871+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:30:42.870+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:30:42.872+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:30:42.895+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-11-20T03:33:26.445+0100] {processor.py:186} INFO - Started process (PID=253244) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:33:26.450+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:33:26.459+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:33:26.456+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:33:26.522+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:33:26.510+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:33:26.526+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:33:26.525+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:33:26.528+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:33:26.561+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.145 seconds
[2024-11-20T03:36:21.726+0100] {processor.py:186} INFO - Started process (PID=253349) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:36:21.728+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:36:21.736+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:36:21.734+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:36:21.778+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:36:21.770+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:36:21.780+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:36:21.779+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:36:21.782+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:36:21.808+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-11-20T03:43:09.247+0100] {processor.py:186} INFO - Started process (PID=253493) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:43:09.250+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:43:09.256+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:43:09.254+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:43:09.314+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:43:09.293+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:43:09.317+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:43:09.316+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:43:09.319+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:43:09.484+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.278 seconds
[2024-11-20T03:48:30.726+0100] {processor.py:186} INFO - Started process (PID=253595) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:48:30.733+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:48:30.751+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:48:30.741+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:48:30.862+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:48:30.839+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:48:30.870+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:48:30.868+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:48:30.872+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:48:30.936+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.254 seconds
[2024-11-20T03:50:32.805+0100] {processor.py:186} INFO - Started process (PID=253664) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:50:32.808+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:50:32.816+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:50:32.813+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:50:32.916+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:50:32.889+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:50:32.921+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:50:32.920+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:50:32.923+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:50:32.963+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.186 seconds
[2024-11-20T03:53:34.340+0100] {processor.py:186} INFO - Started process (PID=253764) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:53:34.342+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:53:34.346+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:53:34.345+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:53:34.374+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:53:34.365+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:53:34.376+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:53:34.375+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:53:34.377+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:53:34.397+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-11-20T03:56:35.757+0100] {processor.py:186} INFO - Started process (PID=253869) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:56:35.760+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:56:35.765+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:56:35.763+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:56:35.845+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:56:35.809+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:56:35.849+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:56:35.847+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:56:35.851+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:56:35.879+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
[2024-11-20T03:58:57.878+0100] {processor.py:186} INFO - Started process (PID=253967) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:58:57.881+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T03:58:57.887+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:58:57.886+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:58:57.940+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:58:57.921+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T03:58:57.947+0100] {logging_mixin.py:190} INFO - [2024-11-20T03:58:57.944+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T03:58:57.950+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T03:58:57.997+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.133 seconds
[2024-11-20T04:01:38.495+0100] {processor.py:186} INFO - Started process (PID=254067) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:01:38.501+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:01:38.507+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:01:38.505+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:01:38.587+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:01:38.557+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:01:38.593+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:01:38.590+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:01:38.597+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:01:38.642+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.165 seconds
[2024-11-20T04:05:32.387+0100] {processor.py:186} INFO - Started process (PID=254171) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:05:32.395+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:05:32.409+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:05:32.405+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:05:32.497+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:05:32.483+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:05:32.501+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:05:32.499+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:05:32.503+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:05:32.537+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.186 seconds
[2024-11-20T04:07:13.505+0100] {processor.py:186} INFO - Started process (PID=254247) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:07:13.510+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:07:13.522+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:07:13.518+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:07:13.569+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:07:13.560+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:07:13.572+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:07:13.570+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:07:13.573+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:07:13.603+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2024-11-20T04:11:35.583+0100] {processor.py:186} INFO - Started process (PID=254379) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:11:35.599+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:11:35.607+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:11:35.604+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:11:35.654+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:11:35.644+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:11:35.657+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:11:35.656+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:11:35.658+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:11:35.682+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-11-20T04:15:47.404+0100] {processor.py:186} INFO - Started process (PID=254460) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:15:47.408+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:15:47.415+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:15:47.412+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:15:47.474+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:15:47.458+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:15:47.476+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:15:47.475+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:15:47.478+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:15:47.585+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.204 seconds
[2024-11-20T04:17:58.854+0100] {processor.py:186} INFO - Started process (PID=254555) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:17:58.868+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:17:58.877+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:17:58.874+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:17:58.924+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:17:58.909+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:17:58.930+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:17:58.927+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:17:58.933+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:17:58.967+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.138 seconds
[2024-11-20T04:20:02.931+0100] {processor.py:186} INFO - Started process (PID=254645) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:20:02.933+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:20:02.938+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:20:02.936+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:20:02.968+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:20:02.961+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:20:02.971+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:20:02.969+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:20:02.972+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:20:02.993+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-11-20T04:22:04.732+0100] {processor.py:186} INFO - Started process (PID=254733) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:22:04.735+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:22:04.740+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:22:04.738+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:22:04.777+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:22:04.768+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:22:04.780+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:22:04.779+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:22:04.782+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:22:04.808+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2024-11-20T04:26:50.481+0100] {processor.py:186} INFO - Started process (PID=254880) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:26:50.485+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:26:50.492+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:26:50.489+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:26:50.563+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:26:50.541+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:26:50.567+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:26:50.565+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:26:50.569+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:26:50.602+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.143 seconds
[2024-11-20T04:28:24.141+0100] {processor.py:186} INFO - Started process (PID=254950) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:28:24.146+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:28:24.154+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:28:24.151+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:28:24.224+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:28:24.209+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:28:24.229+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:28:24.227+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:28:24.231+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:28:24.295+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2024-11-20T04:32:50.160+0100] {processor.py:186} INFO - Started process (PID=255087) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:32:50.162+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:32:50.170+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:32:50.169+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:32:50.217+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:32:50.203+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:32:50.220+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:32:50.219+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:32:50.222+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:32:50.252+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-11-20T04:36:55.311+0100] {processor.py:186} INFO - Started process (PID=255180) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:36:55.314+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:36:55.320+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:36:55.318+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:36:55.381+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:36:55.362+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:36:55.385+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:36:55.383+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:36:55.390+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:36:55.422+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2024-11-20T04:38:33.785+0100] {processor.py:186} INFO - Started process (PID=255253) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:38:33.790+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:38:33.797+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:38:33.794+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:38:33.859+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:38:33.844+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:38:33.864+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:38:33.862+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:38:33.866+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:38:33.893+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
[2024-11-20T04:56:04.127+0100] {processor.py:186} INFO - Started process (PID=255450) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:56:04.130+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:56:04.135+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:56:04.134+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:56:04.235+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:56:04.211+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:56:04.240+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:56:04.238+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:56:04.241+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:56:04.277+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.167 seconds
[2024-11-20T04:57:36.299+0100] {processor.py:186} INFO - Started process (PID=255516) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:57:36.304+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:57:36.314+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:57:36.312+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:57:36.377+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:57:36.351+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:57:36.385+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:57:36.382+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:57:36.391+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:57:36.473+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.201 seconds
[2024-11-20T04:59:38.562+0100] {processor.py:186} INFO - Started process (PID=255605) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:59:38.567+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T04:59:38.576+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:59:38.574+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:59:38.640+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:59:38.628+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T04:59:38.643+0100] {logging_mixin.py:190} INFO - [2024-11-20T04:59:38.642+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T04:59:38.645+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T04:59:38.671+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.193 seconds
[2024-11-20T05:01:43.538+0100] {processor.py:186} INFO - Started process (PID=255694) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T05:01:43.541+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-20T05:01:43.546+0100] {logging_mixin.py:190} INFO - [2024-11-20T05:01:43.544+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T05:01:43.620+0100] {logging_mixin.py:190} INFO - [2024-11-20T05:01:43.608+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-20T05:01:43.624+0100] {logging_mixin.py:190} INFO - [2024-11-20T05:01:43.622+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-20T05:01:43.626+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-20T05:01:43.661+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.140 seconds
