[2024-11-22T02:07:37.871+0100] {processor.py:186} INFO - Started process (PID=9767) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:07:37.873+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:07:37.877+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:07:37.876+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:07:37.905+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:07:37.896+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:07:37.907+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:07:37.906+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:07:37.908+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:07:37.930+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-11-22T02:13:05.310+0100] {processor.py:186} INFO - Started process (PID=9940) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:13:05.361+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:13:05.366+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:13:05.365+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:13:05.426+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:13:05.410+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:13:05.431+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:13:05.429+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:13:05.433+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:13:05.468+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.197 seconds
[2024-11-22T02:14:46.150+0100] {processor.py:186} INFO - Started process (PID=10047) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:14:46.153+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:14:46.160+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:14:46.157+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:14:46.220+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:14:46.206+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:14:46.222+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:14:46.221+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:14:46.223+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:14:46.253+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2024-11-22T02:21:35.537+0100] {processor.py:186} INFO - Started process (PID=10240) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:21:35.540+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:21:35.546+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:21:35.544+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:21:35.613+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:21:35.595+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:21:35.617+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:21:35.616+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:21:35.621+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:21:35.654+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.140 seconds
[2024-11-22T02:23:29.124+0100] {processor.py:186} INFO - Started process (PID=10327) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:23:29.127+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:23:29.132+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:23:29.131+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:23:29.172+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:23:29.158+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:23:29.175+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:23:29.174+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:23:29.176+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:23:29.197+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2024-11-22T02:25:50.836+0100] {processor.py:186} INFO - Started process (PID=10420) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:25:50.838+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:25:50.843+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:25:50.842+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:25:50.892+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:25:50.884+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:25:50.895+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:25:50.894+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:25:50.898+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:25:50.917+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-11-22T02:27:19.351+0100] {processor.py:186} INFO - Started process (PID=10474) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:27:19.353+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:27:19.358+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:27:19.356+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:27:19.397+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:27:19.387+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:27:19.400+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:27:19.399+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:27:19.401+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:27:19.423+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2024-11-22T02:29:24.329+0100] {processor.py:186} INFO - Started process (PID=10564) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:29:24.331+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:29:24.333+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:29:24.333+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:29:24.351+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:29:24.346+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:29:24.352+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:29:24.351+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:29:24.352+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:29:24.364+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-11-22T02:31:19.702+0100] {processor.py:186} INFO - Started process (PID=10647) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:31:19.704+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:31:19.707+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:31:19.706+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:31:19.742+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:31:19.731+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:31:19.744+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:31:19.743+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:31:19.745+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:31:19.762+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-11-22T02:33:10.171+0100] {processor.py:186} INFO - Started process (PID=10745) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:33:10.173+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:33:10.176+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:33:10.175+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:33:10.207+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:33:10.199+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:33:10.209+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:33:10.208+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:33:10.210+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:33:10.231+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-11-22T02:35:11.319+0100] {processor.py:186} INFO - Started process (PID=10843) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:35:11.321+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T02:35:11.324+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:35:11.323+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:35:11.440+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:35:11.430+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T02:35:11.443+0100] {logging_mixin.py:190} INFO - [2024-11-22T02:35:11.442+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T02:35:11.445+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T02:35:11.467+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.160 seconds
[2024-11-22T03:00:17.510+0100] {processor.py:186} INFO - Started process (PID=11166) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:00:17.513+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:00:17.518+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:00:17.516+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:00:17.558+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:00:17.546+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:00:17.560+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:00:17.559+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:00:17.562+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:00:17.588+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-11-22T03:01:49.939+0100] {processor.py:186} INFO - Started process (PID=11231) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:01:49.942+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:01:49.946+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:01:49.945+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:01:49.981+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:01:49.971+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:01:49.982+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:01:49.982+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:01:49.983+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:01:50.001+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2024-11-22T03:03:47.866+0100] {processor.py:186} INFO - Started process (PID=11323) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:03:47.869+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:03:47.872+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:03:47.871+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:03:47.905+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:03:47.896+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:03:47.907+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:03:47.906+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:03:47.909+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:03:47.931+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-11-22T03:13:00.431+0100] {processor.py:186} INFO - Started process (PID=11599) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:13:00.433+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:13:00.439+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:13:00.438+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:13:00.469+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:13:00.461+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:13:00.472+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:13:00.471+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:13:00.473+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:13:00.494+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2024-11-22T03:14:20.731+0100] {processor.py:186} INFO - Started process (PID=11658) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:14:20.733+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:14:20.737+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:14:20.736+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:14:20.767+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:14:20.759+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:14:20.769+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:14:20.768+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:14:20.770+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:14:20.786+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-11-22T03:16:07.626+0100] {processor.py:186} INFO - Started process (PID=11764) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:16:07.629+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:16:07.634+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:16:07.632+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:16:07.686+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:16:07.671+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:16:07.691+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:16:07.689+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:16:07.692+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:16:07.723+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2024-11-22T03:18:12.606+0100] {processor.py:186} INFO - Started process (PID=11863) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:18:12.608+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:18:12.611+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:18:12.610+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:18:12.639+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:18:12.629+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:18:12.641+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:18:12.640+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:18:12.642+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:18:12.658+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-11-22T03:20:18.132+0100] {processor.py:186} INFO - Started process (PID=11947) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:20:18.135+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:20:18.138+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:20:18.137+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:20:18.171+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:20:18.164+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:20:18.173+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:20:18.173+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:20:18.175+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:20:18.202+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-11-22T03:22:10.810+0100] {processor.py:186} INFO - Started process (PID=12028) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:22:10.814+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:22:10.818+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:22:10.817+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:22:10.869+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:22:10.855+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:22:10.872+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:22:10.870+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:22:10.874+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:22:10.901+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.112 seconds
[2024-11-22T03:24:08.938+0100] {processor.py:186} INFO - Started process (PID=12108) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:24:08.941+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:24:08.944+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:24:08.943+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:24:08.972+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:24:08.965+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:24:08.974+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:24:08.973+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:24:08.975+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:24:08.991+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-11-22T03:25:54.238+0100] {processor.py:186} INFO - Started process (PID=12189) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:25:54.240+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:25:54.243+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:25:54.242+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:25:54.273+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:25:54.265+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:25:54.275+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:25:54.274+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:25:54.277+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:25:54.299+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2024-11-22T03:35:17.501+0100] {processor.py:186} INFO - Started process (PID=12425) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:35:17.503+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:35:17.506+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:35:17.505+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:35:17.529+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:35:17.521+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:35:17.531+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:35:17.530+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:35:17.532+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:35:17.546+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2024-11-22T03:36:47.698+0100] {processor.py:186} INFO - Started process (PID=12483) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:36:47.702+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:36:47.707+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:36:47.706+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:36:47.738+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:36:47.730+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:36:47.740+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:36:47.739+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:36:47.741+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:36:47.760+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-11-22T03:38:45.947+0100] {processor.py:186} INFO - Started process (PID=12566) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:38:45.949+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:38:45.953+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:38:45.952+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:38:45.988+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:38:45.980+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:38:45.990+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:38:45.989+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:38:45.991+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:38:46.008+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2024-11-22T03:40:39.606+0100] {processor.py:186} INFO - Started process (PID=12648) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:40:39.608+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:40:39.611+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:40:39.610+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:40:39.634+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:40:39.628+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:40:39.636+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:40:39.635+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:40:39.637+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:40:39.652+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-11-22T03:42:36.418+0100] {processor.py:186} INFO - Started process (PID=12757) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:42:36.419+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:42:36.422+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:42:36.421+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:42:36.438+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:42:36.433+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:42:36.439+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:42:36.439+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:42:36.440+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:42:36.452+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-22T03:48:01.226+0100] {processor.py:186} INFO - Started process (PID=12907) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:48:01.228+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:48:01.233+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:48:01.232+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:48:01.281+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:48:01.271+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:48:01.284+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:48:01.283+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:48:01.286+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:48:01.310+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2024-11-22T03:49:33.935+0100] {processor.py:186} INFO - Started process (PID=13024) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:49:33.937+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:49:33.940+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:49:33.939+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:49:33.972+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:49:33.963+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:49:33.974+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:49:33.973+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:49:33.975+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:49:33.992+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-11-22T03:51:37.499+0100] {processor.py:186} INFO - Started process (PID=13145) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:51:37.502+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:51:37.507+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:51:37.506+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:51:37.554+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:51:37.545+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:51:37.556+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:51:37.555+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:51:37.558+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:51:37.579+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.579 seconds
[2024-11-22T03:53:36.443+0100] {processor.py:186} INFO - Started process (PID=13253) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:53:36.445+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T03:53:36.448+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:53:36.447+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:53:36.483+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:53:36.474+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T03:53:36.485+0100] {logging_mixin.py:190} INFO - [2024-11-22T03:53:36.484+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T03:53:36.486+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T03:53:36.506+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2024-11-22T04:09:56.850+0100] {processor.py:186} INFO - Started process (PID=13583) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:09:56.851+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:09:56.854+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:09:56.853+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:09:56.876+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:09:56.869+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:09:56.878+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:09:56.877+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:09:56.879+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:09:56.901+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-11-22T04:29:20.470+0100] {processor.py:186} INFO - Started process (PID=14081) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:29:20.475+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:29:20.480+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:29:20.478+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:29:20.521+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:29:20.512+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:29:20.524+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:29:20.523+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:29:20.525+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:29:20.558+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-11-22T04:31:15.753+0100] {processor.py:186} INFO - Started process (PID=14144) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:31:15.756+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:31:15.763+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:31:15.760+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:31:15.826+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:31:15.812+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:31:15.830+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:31:15.828+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:31:15.833+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:31:15.868+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
[2024-11-22T04:33:27.420+0100] {processor.py:186} INFO - Started process (PID=14232) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:33:27.422+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:33:27.426+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:33:27.425+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:33:27.454+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:33:27.447+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:33:27.456+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:33:27.455+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:33:27.457+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:33:27.478+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-11-22T04:35:52.438+0100] {processor.py:186} INFO - Started process (PID=14334) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:35:52.440+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:35:52.444+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:35:52.443+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:35:52.487+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:35:52.481+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:35:52.489+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:35:52.488+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:35:52.491+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:35:52.511+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2024-11-22T04:38:10.862+0100] {processor.py:186} INFO - Started process (PID=14422) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:38:10.869+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:38:10.873+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:38:10.872+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:38:10.899+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:38:10.892+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:38:10.901+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:38:10.900+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:38:10.902+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:38:10.918+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-11-22T04:44:48.155+0100] {processor.py:186} INFO - Started process (PID=14623) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:44:48.158+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:44:48.170+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:44:48.162+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:44:48.462+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:44:48.253+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:44:48.467+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:44:48.465+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:44:48.468+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:44:48.504+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.381 seconds
[2024-11-22T04:47:05.113+0100] {processor.py:186} INFO - Started process (PID=14693) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:47:05.116+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:47:05.123+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:47:05.121+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:47:05.197+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:47:05.174+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:47:05.202+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:47:05.200+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:47:05.204+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:47:05.236+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.145 seconds
[2024-11-22T04:49:03.898+0100] {processor.py:186} INFO - Started process (PID=14744) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:49:03.904+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:49:03.909+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:49:03.908+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:49:04.032+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:49:03.973+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:49:04.070+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:49:04.062+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:49:04.076+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:49:04.147+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.284 seconds
[2024-11-22T04:51:35.624+0100] {processor.py:186} INFO - Started process (PID=14838) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:51:35.629+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:51:35.636+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:51:35.634+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:51:35.683+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:51:35.668+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:51:35.696+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:51:35.685+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:51:35.698+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:51:35.739+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2024-11-22T04:53:58.041+0100] {processor.py:186} INFO - Started process (PID=14928) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:53:58.044+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:53:58.052+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:53:58.049+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:53:58.128+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:53:58.109+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:53:58.134+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:53:58.131+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:53:58.136+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:53:58.182+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.185 seconds
[2024-11-22T04:56:33.818+0100] {processor.py:186} INFO - Started process (PID=15038) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:56:33.824+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T04:56:33.829+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:56:33.827+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:56:33.863+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:56:33.854+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T04:56:33.865+0100] {logging_mixin.py:190} INFO - [2024-11-22T04:56:33.864+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T04:56:33.866+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T04:56:33.887+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-11-22T05:00:40.477+0100] {processor.py:186} INFO - Started process (PID=15143) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:00:40.480+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:00:40.486+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:00:40.484+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:00:40.528+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:00:40.515+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:00:40.531+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:00:40.530+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:00:40.533+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:00:40.560+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2024-11-22T05:02:22.740+0100] {processor.py:186} INFO - Started process (PID=15199) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:02:22.743+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:02:22.751+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:02:22.747+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:02:22.788+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:02:22.781+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:02:22.789+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:02:22.789+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:02:22.790+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:02:22.812+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2024-11-22T05:03:51.315+0100] {processor.py:186} INFO - Started process (PID=15248) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:03:51.318+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:03:51.325+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:03:51.323+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:03:51.387+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:03:51.370+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:03:51.392+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:03:51.390+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:03:51.394+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:03:51.427+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
[2024-11-22T05:06:01.458+0100] {processor.py:186} INFO - Started process (PID=15337) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:06:01.461+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:06:01.496+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:06:01.465+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:06:01.688+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:06:01.678+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:06:01.689+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:06:01.689+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:06:01.691+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:06:01.713+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.269 seconds
[2024-11-22T05:08:24.455+0100] {processor.py:186} INFO - Started process (PID=15428) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:08:24.460+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:08:24.465+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:08:24.464+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:08:24.544+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:08:24.523+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:08:24.548+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:08:24.547+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:08:24.552+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:08:24.584+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.146 seconds
[2024-11-22T05:10:00.791+0100] {processor.py:186} INFO - Started process (PID=15482) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:10:00.793+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:10:00.797+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:10:00.796+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:10:00.826+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:10:00.819+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:10:00.828+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:10:00.827+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:10:00.829+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:10:00.853+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2024-11-22T05:12:22.614+0100] {processor.py:186} INFO - Started process (PID=15571) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:12:22.618+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:12:22.623+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:12:22.622+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:12:22.649+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:12:22.644+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:12:22.652+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:12:22.651+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:12:22.653+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:12:22.681+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-11-22T05:14:37.714+0100] {processor.py:186} INFO - Started process (PID=15658) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:14:37.716+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:14:37.720+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:14:37.719+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:14:37.748+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:14:37.740+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:14:37.750+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:14:37.750+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:14:37.751+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:14:37.773+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2024-11-22T05:16:11.904+0100] {processor.py:186} INFO - Started process (PID=15710) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:16:11.910+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:16:11.919+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:16:11.916+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:16:12.110+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:16:12.083+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:16:12.117+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:16:12.114+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:16:12.118+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:16:12.164+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.281 seconds
[2024-11-22T05:18:36.341+0100] {processor.py:186} INFO - Started process (PID=15804) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:18:36.345+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:18:36.352+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:18:36.350+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:18:36.431+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:18:36.412+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:18:36.434+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:18:36.433+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:18:36.439+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:18:36.488+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.174 seconds
[2024-11-22T05:19:59.639+0100] {processor.py:186} INFO - Started process (PID=15856) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:19:59.641+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:19:59.646+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:19:59.644+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:19:59.669+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:19:59.664+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:19:59.671+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:19:59.671+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:19:59.672+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:19:59.691+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-11-22T05:22:03.449+0100] {processor.py:186} INFO - Started process (PID=15938) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:22:03.452+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:22:03.457+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:22:03.455+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:22:03.511+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:22:03.495+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:22:03.515+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:22:03.513+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:22:03.518+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:22:03.586+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.154 seconds
[2024-11-22T05:24:07.723+0100] {processor.py:186} INFO - Started process (PID=16030) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:24:07.731+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:24:07.735+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:24:07.734+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:24:07.766+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:24:07.757+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:24:07.768+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:24:07.767+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:24:07.769+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:24:07.788+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-11-22T05:25:58.230+0100] {processor.py:186} INFO - Started process (PID=16115) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:25:58.233+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:25:58.239+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:25:58.238+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:25:58.295+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:25:58.287+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:25:58.299+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:25:58.297+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:25:58.300+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:25:58.324+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2024-11-22T05:27:49.897+0100] {processor.py:186} INFO - Started process (PID=16198) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:27:49.899+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:27:49.901+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:27:49.900+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:27:49.915+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:27:49.912+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:27:49.916+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:27:49.916+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:27:49.917+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:27:49.930+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-22T05:29:35.849+0100] {processor.py:186} INFO - Started process (PID=16277) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:29:35.851+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:29:35.855+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:29:35.854+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:29:35.883+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:29:35.877+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:29:35.886+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:29:35.885+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:29:35.887+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:29:35.907+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-11-22T05:31:20.726+0100] {processor.py:186} INFO - Started process (PID=16354) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:31:20.731+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:31:20.735+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:31:20.734+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:31:20.799+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:31:20.788+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:31:20.800+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:31:20.800+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:31:20.801+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:31:20.827+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2024-11-22T05:33:06.286+0100] {processor.py:186} INFO - Started process (PID=16434) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:33:06.288+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:33:06.292+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:33:06.290+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:33:06.320+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:33:06.314+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:33:06.321+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:33:06.321+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:33:06.322+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:33:06.335+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-11-22T05:35:17.305+0100] {processor.py:186} INFO - Started process (PID=16523) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:35:17.308+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:35:17.312+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:35:17.311+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:35:17.343+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:35:17.336+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:35:17.345+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:35:17.345+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:35:17.347+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:35:17.364+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2024-11-22T05:37:21.553+0100] {processor.py:186} INFO - Started process (PID=16607) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:37:21.557+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:37:21.561+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:37:21.560+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:37:21.585+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:37:21.577+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:37:21.586+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:37:21.586+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:37:21.587+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:37:21.607+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-11-22T05:39:13.016+0100] {processor.py:186} INFO - Started process (PID=16692) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:39:13.020+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:39:13.025+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:39:13.023+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:39:13.068+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:39:13.056+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:39:13.070+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:39:13.069+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:39:13.071+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:39:13.097+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2024-11-22T05:41:07.078+0100] {processor.py:186} INFO - Started process (PID=16776) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:41:07.081+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:41:07.087+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:41:07.085+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:41:07.138+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:41:07.123+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:41:07.142+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:41:07.140+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:41:07.144+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:41:07.167+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2024-11-22T05:43:02.534+0100] {processor.py:186} INFO - Started process (PID=16859) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:43:02.537+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:43:02.541+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:43:02.540+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:43:02.577+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:43:02.568+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:43:02.578+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:43:02.578+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:43:02.580+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:43:02.600+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2024-11-22T05:45:07.527+0100] {processor.py:186} INFO - Started process (PID=16946) to work on /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:45:07.528+0100] {processor.py:914} INFO - Processing file /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-22T05:45:07.532+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:45:07.531+0100] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:45:07.564+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:45:07.553+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-22T05:45:07.566+0100] {logging_mixin.py:190} INFO - [2024-11-22T05:45:07.565+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-22T05:45:07.567+0100] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-22T05:45:07.589+0100] {processor.py:208} INFO - Processing /mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
